services:
  keme:
    build: .
    ports:
      - "3018:3000"
    volumes:
      - "/docker/appdata/keme:/config:rw"
      - "./openbox:/config/.config/openbox/:rw"
    # environment:
    #   CLI_ARGS: ...
